# Generated by Django 4.2.4 on 2023-09-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='SubCategories',
            new_name='SubCategorie',
        ),
    ]
