# Generated by Django 4.2.4 on 2023-09-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_categories_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
