# Generated by Django 4.2.5 on 2023-10-03 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='SubCategorie',
            new_name='SubCategories',
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('category',)},
        ),
        migrations.AlterModelOptions(
            name='subcategories',
            options={'ordering': ('sub_category',)},
        ),
    ]
