# Generated by Django 4.2.4 on 2023-10-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_categories_options_alter_subcategories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='image',
            field=models.ImageField(default=1, upload_to='sub_categories/'),
            preserve_default=False,
        ),
    ]
